### ISSUE TITLE
Make sure that there is a single report for all of the tests in Testing/

### ISSUE THREAD

**Issue by arcfide** [arcfide/Co-dfns#187]
Part of #131

**Comment by arcfide** [comment]
This is getting really annoying, so we need to make this happen soon for sanity's sake.

**Comment by gavwhela** [comment]
I agree that this is a priority.

**Comment by arcfide** [comment]
I've taken a look at this and the actual work isn't too hard, but it requires editing APLUnit to get the behavior right, so that is less than ideal. It's not clear whether this should be made an option or not. I think not, so I will make the changes assuming a single report and then make a pull request upstream to see if @Gianfrancoalongi likes it.

**Comment by gavwhela** [comment]
An additional optimization that might be nice is not to have the tests that are not being run, such as when you restrict the testing framework to not test some of the available compiler backends, not be counted as passed tests. This is fairly low priority however...

**Comment by arcfide** [comment]
I agree that this might be interesting. It would be even neater to have a "not run" feature.

**Comment by arcfide** [comment]
I've created #227 to handle skipping tests separately from this one.
