### ISSUE TITLE
Don't include skipped tests in the passed tests

### ISSUE THREAD

**Issue by arcfide** [arcfide/Co-dfns#227]
In #187 @gavwhela suggested having the test suite not include the tests that were not run as a part of the passed tests. This seems like a neat feature that we should put in. I am going to file the following issue upstream and see what they say.

https://github.com/Gianfrancoalongi/APLUnit/issues/22

**Comment by Gianfrancoalongi** [comment]
I read through the original #187 and see the issue - so sure, let us make the change for the better!

**Comment by arcfide** [comment]
This is now no longer an issue since we don't have skipped tests anymore.
