### ISSUE TITLE
Scan inconsistent with dyalog

### ISSUE THREAD

**Issue by harporoeder** [arcfide/Co-dfns#284]
The code:

    u←{<\⍵}

Run with:

    u 2 10 ⍴ 1

On Dyalog produces:

    1 0 0 0 0 0 0 0 0 0
    1 0 0 0 0 0 0 0 0 0

On the compiler produces:

    1 1 1 1 1 1 1 1 0 0
    0 0 0 0 0 0 0 0 0 0

**Comment by arcfide** [comment]
Scan on Booleans currently has a bug in it. This should be fixed soon.
