### ISSUE TITLE
Dot operator crashes

### ISSUE THREAD

**Issue by harporoeder** [arcfide/Co-dfns#287]
Take the code:

    f←{⍵∘.=⍵}

Run with:

    f 0 0 0 1 1 1 1 1

On Dyalog produces:
```

1 1 1 0	0 0 0 0
1 1 1 0	0 0 0 0
1 1 1 0	0 0 0 0
0 0 0 1	1 1 1 1
0 0 0 1	1 1 1 1
0 0 0 1	1 1 1 1
0 0 0 1	1 1 1 1
0 0 0 1	1 1 1 1
```

With the compiler it crashes.

**Comment by arcfide** [comment]
*sigh* You're killing me smalls. :-)
