### ISSUE TITLE
Dot operator fails with computed parameter

### ISSUE THREAD

**Issue by harporoeder** [arcfide/Co-dfns#288]
Take the code:

    f←{(∪⍵)∘.=⍵}

Run with:

   f 0 0 0 1 1 1 1 1

The expected result is:

    1 1 1 0 0 0 0 0
    0 0 0 1 1 1 1 1

But the compiler produces the error:

`
NONCE ERROR    
f[0] f←{_←'dya'⎕NA'build/analytics_gcc.so|f >PP <PP <PP' ⋄ _←'mon'⎕NA'build/analytics_gcc.so|f >PP
      P <PP' ⋄ 0=⎕NC'⍺':mon 0 0 ⍵ ⋄ dya 0 ⍺ ⍵} ⋄ 0
`

**Comment by harporoeder** [comment]
Are these reports I have been giving you on bugs or are these features you have knowingly not implemented? If they are things knowingly not implemented I can probably find work arounds. I don't want to force a bunch of feature dev taking up your time.

**Comment by arcfide** [comment]
You're basically running into the cases where Boolean values are not fully implemented on some primitives.
