### ISSUE TITLE
Reshape returns left most parameters when parenthesis used

### ISSUE THREAD

**Issue by harporoeder** [arcfide/Co-dfns#290]
The code:

    f←{2 (3×4)⍴⍵}

Run with:

    f⍳4

Produces:

    2

The code:

    f←{2 12⍴⍵}

Produces:

    0 1 2 3 0 1 2 3 0 1 2 3
    0 1 2 3 0 1 2 3 0 1 2 3

The code:

    f←{(3×4) 2⍴⍵}

Produces:

    12

The code:

    f←{2 3 (3+1) 2⍴⍵}

Produces:

    2 3

The code:

    f←{2 (2+1) (4+0) 2⍴⍵}

Produces:

    2

**Comment by arcfide** [comment]
Aaaah! Finally, something that's not actually unintentional or unimplemented. :-P This is expected behavior right now because we do not support stranding. To do what you want, you should be doing something like `(2,(3×4))⍴⍵`. Hope this helps!
