### ISSUE TITLE
Non deterministic malloc error

### ISSUE THREAD

**Issue by gavwhela** [arcfide/Co-dfns#291]
This is the error we're getting sometimes, it happens on what I believe to be identical requests into the generated Co-dfns shared object from C++. 

main: malloc.c:2392: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

I don't have a core for you, will need to configure to save it and do some more testing, but wanted to get this issue in for the moment.

@harporoeder says that he has had a similar error in the dyalog mapl environment, when the Co-dfns namespace is loaded.

**Comment by arcfide** [comment]
I'm playing around with a new backend that should help to mitigate this issue, hopefully you should see it integrated into master this month.

**Comment by arcfide** [comment]
This is no longer an issue with the new backend.
